version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
#   command: --check-caps false
    volumes:
      - ./output:/home/irisowner/irisdev/app/output/
    ports: 
      - 32782:1972
      - 32783:52773
      - 32784:53773
    command: 
      - -a
      - iris session iris -U%SYS '##class(Security.Users).UnExpireUserPasswords("*")'
      - --check-caps false
